/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookCounter;

/**
 *
 * @author taloh
 */
public class Assignment_7_BookCounterUI extends javax.swing.JFrame {

    /**
     * Creates new form Assignment_7_BookCounterUI
     */
    public Assignment_7_BookCounterUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        m_tlTitle = new javax.swing.JLabel();
        m_jlNow = new javax.swing.JLabel();
        m_tlBoughtSold = new javax.swing.JLabel();
        m_tfNow = new javax.swing.JTextField();
        m_tfBoughtSold = new javax.swing.JTextField();
        m_btnBought = new javax.swing.JButton();
        m_btnSold = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        m_tlTitle.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        m_tlTitle.setText("How many books do you have?");

        m_jlNow.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        m_jlNow.setText("Current Library Amount:");

        m_tlBoughtSold.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        m_tlBoughtSold.setText("Amount that you have bought or sold:");

        m_btnBought.setBackground(new java.awt.Color(102, 102, 255));
        m_btnBought.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        m_btnBought.setForeground(new java.awt.Color(255, 255, 255));
        m_btnBought.setText("Bought");
        m_btnBought.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnBoughtActionPerformed(evt);
            }
        });

        m_btnSold.setBackground(new java.awt.Color(102, 102, 255));
        m_btnSold.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        m_btnSold.setForeground(new java.awt.Color(255, 255, 255));
        m_btnSold.setText("Sold");
        m_btnSold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnSoldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(m_btnBought)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(m_btnSold)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m_tlBoughtSold)
                .addGap(18, 18, 18)
                .addComponent(m_tfBoughtSold)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m_tlTitle)
                        .addContainerGap(101, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(m_jlNow)
                        .addGap(18, 18, 18)
                        .addComponent(m_tfNow)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(m_tlTitle)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_jlNow)
                    .addComponent(m_tfNow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_tlBoughtSold)
                    .addComponent(m_tfBoughtSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_btnBought)
                    .addComponent(m_btnSold))
                .addGap(0, 53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setNow(Float value){
        m_tfNow.setText(Float.toString(value));
    }
    private Float getNow(){
        return Float.parseFloat(m_tfNow.getText());
    }
    private void setBoughtSold(Float value){
        m_tfBoughtSold.setText(Float.toString(value));
    }
    private Float getBoughtSold(){
        return Float.parseFloat(m_tfBoughtSold.getText());
    }             

    private void m_btnBoughtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnBoughtActionPerformed
        Float Now = getNow();
        Float TransAmt = getBoughtSold();
        setNow(Now + TransAmt);
    }//GEN-LAST:event_m_btnBoughtActionPerformed

    private void m_btnSoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnSoldActionPerformed
       Float Now = getNow();
       Float  TransAmt = getBoughtSold();
       setNow(Now - TransAmt);

    }//GEN-LAST:event_m_btnSoldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment_7_BookCounterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment_7_BookCounterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment_7_BookCounterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment_7_BookCounterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment_7_BookCounterUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton m_btnBought;
    private javax.swing.JButton m_btnSold;
    private javax.swing.JLabel m_jlNow;
    private javax.swing.JTextField m_tfBoughtSold;
    private javax.swing.JTextField m_tfNow;
    private javax.swing.JLabel m_tlBoughtSold;
    private javax.swing.JLabel m_tlTitle;
    // End of variables declaration//GEN-END:variables
}
